config/routes.rb
Rails.application.routes.draw do
  resources :places
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :except => [:home]
    protected
    def after_sign_in_path_for(resource)
      request.env['omniauth.origin'] || stored_location_for(resource) || places_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        
    end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
      if @place.save
        flash[:notice] = "Place was successfully created."
        redirect_to places_path
    else
        render 'new'
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    if @place.update(place_params)
      flash[:notice] = "Place was successfully updatabe"
      redirect_to @place
    else
      render 'edit'
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    flash[:danger] = "Place was successfully deleted"
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/_footer.html.erb
<div class = "container">
    <footer class= "footer">
        <small>
            Copyright &copy; <a href = "https://www.udemy.com/"> the complete Ruby on rails Developer</a>
            by <a href = "https://www.linkedin.com/in/sebastian-quintero-garcia-b9332a182/"> Sebastian Quintero</a>
            <a href = "https://www.linkedin.com/in/juan-fernando-tabares-ocampo-338902175/"> Juan Fernando Tabares</a>
        </small>
        <nav>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<br>
<div class="row" id="messagess">
    <div class="col-sm-10 col-sm-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%="#{name}"%>'>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <% if notice%>
                    <%= content_tag :div, msg, :id =>"#{name}", class:"alert alert-success" if msg.is_a?(String) %>
                <%else%>
                    <%= content_tag :div, msg, :id =>"#{name}", class:"alert " if msg.is_a?(String) %>
                <% end %>   

            </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name='turbolinks-visit-control' content='reload'>
  ...
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyAesrd8ZAcN5-MM9aveg3UDr4u8MatSR6A' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
...


    <title>LocationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body id="body">
  <%= render 'shared/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="page-header">
</div>
<div align="center" class="jumbotron"
<p> Welcome with this app you are expected to have access to a 
  							database of places as well as be able to add the sites of 
 						 	preference</p>

</div>

app/views/pages/maps.html.erb
<p>
<%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&center=#{@place.latitude},#{@place.longitude}&key=AIzaSyAesrd8ZAcN5-MM9aveg3UDr4u8MatSR6A", alt: "Map" %>

</p>

app/views/places/_form.html.erb
<div class= 'row'>
  <div class = 'col-sm-12'>
    <% provide :head_tags do %>
      <meta name='turbolinks-visit-control' content='reload'>
      <script>
          document.addEventListener("DOMContentLoaded", initMap2);
      </script>
    <% end %>

    <%= form_with(model: place, local: true) do |form| %>

      
      <% if place.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

          <ul>
          <% place.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group row">
        <div class = "control-label col-sm-1"> 
          <%= form.label :name%>
        </div>
        <div class="col-sm-3">
          <%= form.text_field :name, class:"form-control", placeholder: "Name", autofocus:true  %>
        </div>
        <div class = "control-label col-sm-1"> 
          <%= form.label :latitude %>
        </div>
        <div class="col-sm-3">
        <%= form.text_field :latitude, class:"form-control" %>
        </div>
        <div class="control-label col-sm-1">
          <%= form.label :longitude %>
        </div>
        <div class="col-sm-3">
          <%= form.text_field :longitude, class:"form-control" %>
        </div>
        
      
    </div>
    <div class = "col-sm-10 offset-sm-5">
        <%= form.submit(@place.new_record? ? "Create" : "Update Place", class:"btn btn-primary btn-lg") %>
        </div>
     <div>

      <p>
      <div id="map2"></div>
      </p>
      </div>
      

     
    
    <% end %>
</div>
</div>

app/views/places/edit.html.erb
<h1 align="center">Editing Place</h1>
<%= render 'form', place: @place %>

<%= link_to 'Show', @place, class:"btn btn-info "%> 
<%= link_to 'Back', places_path, class:"btn  btn-success " %>

app/views/places/index.html.erb
<h1 align="center">Places</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th id="font">Name</th>
      <th id="font">Latitude</th>
      <th id="font">Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <div class="row">
          <div class="col-sm-8 offset-sm-2 title-description">
            <td id="font"><%= place.name %></td>
            <td ><%= place.latitude %></td>
            <td ><%= place.longitude %></td>
            <td><%= link_to 'Show', place, class:"btn btn-sm btn-info"%></td>
            <td><%= link_to 'Edit', edit_place_path(place), class:"btn btn-sm btn-primary" %></td>
            <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger"%></td>
          </div>  
        </div>    
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path, class:"btn btn-primary btn-lg" %>

app/views/places/new.html.erb
<h1 align="center">New Place</h1>

<%= render 'form', place: @place %>

app/views/places/show.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
  document.addEventListener("DOMContentLoaded", function(){
      initMap(<%=@place.latitude%>, <%=@place.longitude%>)
  });
  </script>
<% end %>
<table class="table table-condensed">
  <thead>
    <tr>
      <%= notice %>
      
      <th id="font">Name</th> 
      <th id="font">Latitude</th>
      <th id="font">Longitude</th>
    </tr>
  </thead>
  <tbody>
    <td id="font"><%= @place.name %></td>
    <td id="font"><%= @place.latitude %></td>  
    <td id="font"><%= @place.longitude %></td>
  </tbody>
</table>
<div class="form-group row col-sm-offset-4">
  <div class = "col-sm-5">
    <%= link_to 'Edit', edit_place_path(@place), class:"btn btn-block btn-primary " %> 
    <%= link_to 'Back', places_path, class:"btn btn-success btn-block" %>
  </div>  
</div>
<p>
    <div id="map"></div>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class='row'>
      <div class="col-xs-4 col-xs-offset-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">
                  <%= pluralize(obj.errors.count, "error") %>
                  prohibited this login from being saved:
                </h2>
                <div class="panel-body">
                  <ul>
                    <% obj.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul> 
                </div>
              </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Location", root_path, class:"navbar-brand" , id:"logo" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "List of Places", places_path %></li>
      </ul>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <p class="navbar-text">
          Signed in as <%= "#{current_user.email}" %> 
        </p>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li> 
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>